// <auto-generated />
namespace Training_Application_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddMin24HrstoTraining : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMin24HrstoTraining));
        
        string IMigrationMetadata.Id
        {
            get { return "202111071045173_AddMin24HrstoTraining"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
